stages:
  download_train_data:
    cmd: python fashmnistmlpipeline/download_data.py True processed
    deps:
    - fashmnistmlpipeline/download_data.py
    outs:
    - data/FashionMNIST/processed
    - data/FashionMNIST/raw
  train_model:
    cmd: python fashmnistmlpipeline/train.py
    deps:
    - data/FashionMNIST/processed
    - fashmnistmlpipeline/train.py
    params:
    - fashmnistmlpipeline/params.yml:
      - train
    outs:
    - data/model/learner.pkl
    - data/model/model.pth
    metrics:
    - data/model/results.json
    plots:
    - data/model/actual_vs_predicted.csv:
        template: confusion
        x: actual
        y: predicted
        title: Confusion Matrix
