stages:
  download_train_data:
    cmd: python fashmnistmlpipeline/download_data.py True processed
    deps:
    - fashmnistmlpipeline/download_data.py
    outs:
    - data/FashionMNIST/processed
    - data/FashionMNIST/raw
  train_model:
    cmd: python fashmnistmlpipeline/train.py
    deps:
    - data/FashionMNIST/processed
    - fashmnistmlpipeline/train.py
    params:
    - fashmnistmlpipeline/params.yml:
      - train
    outs:
    - data/model/learner.pkl
    - data/model/model.pth
    metrics:
    - data/model/results.json
    plots:
    - data/model/actual_vs_predicted.csv:
        template: confusion
        x: actual
        y: predicted
        title: Validation Confusion Matrix
  download_test_data:
    cmd: python fashmnistmlpipeline/download_data.py False test
    outs:
    - data/FashionMNIST/test
  evaluate:
    cmd: python fashmnistmlpipeline/evaluate.py
    deps:
    - data/model/learner.pkl
    - data/FashionMNIST/test
    - fashmnistmlpipeline/evaluate.py
    metrics:
    - data/model/test_results.json
    plots:
    - data/model/test_actual_vs_predicted.csv:
        template: confusion
        x: actual
        y: predicted
        title: Test Confusion Matrix
